// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/superkomputer/apiclient/models"
)

// CreateAccountReader is a Reader for the CreateAccount structure.
type CreateAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewCreateAccountAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewCreateAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCreateAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateAccountAccepted creates a CreateAccountAccepted with default headers values
func NewCreateAccountAccepted() *CreateAccountAccepted {
	return &CreateAccountAccepted{}
}

/*CreateAccountAccepted handles this case with default header values.

create payable account of a user on cluster has been accepted
*/
type CreateAccountAccepted struct {
}

func (o *CreateAccountAccepted) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/account/{username}][%d] createAccountAccepted ", 202)
}

func (o *CreateAccountAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAccountNotFound creates a CreateAccountNotFound with default headers values
func NewCreateAccountNotFound() *CreateAccountNotFound {
	return &CreateAccountNotFound{}
}

/*CreateAccountNotFound handles this case with default header values.

The cluster was not found
*/
type CreateAccountNotFound struct {
	Payload *models.Error
}

func (o *CreateAccountNotFound) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/account/{username}][%d] createAccountNotFound  %+v", 404, o.Payload)
}

func (o *CreateAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountDefault creates a CreateAccountDefault with default headers values
func NewCreateAccountDefault(code int) *CreateAccountDefault {
	return &CreateAccountDefault{
		_statusCode: code,
	}
}

/*CreateAccountDefault handles this case with default header values.

Error
*/
type CreateAccountDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create account default response
func (o *CreateAccountDefault) Code() int {
	return o._statusCode
}

func (o *CreateAccountDefault) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/account/{username}][%d] createAccount default  %+v", o._statusCode, o.Payload)
}

func (o *CreateAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
