// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/superkomputer/apiclient/models"
)

// DeleteAccountReader is a Reader for the DeleteAccount structure.
type DeleteAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewDeleteAccountAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteAccountAccepted creates a DeleteAccountAccepted with default headers values
func NewDeleteAccountAccepted() *DeleteAccountAccepted {
	return &DeleteAccountAccepted{}
}

/*DeleteAccountAccepted handles this case with default header values.

delete account task has been accepted
*/
type DeleteAccountAccepted struct {
}

func (o *DeleteAccountAccepted) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{clusterId}/account/{username}][%d] deleteAccountAccepted ", 202)
}

func (o *DeleteAccountAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAccountNotFound creates a DeleteAccountNotFound with default headers values
func NewDeleteAccountNotFound() *DeleteAccountNotFound {
	return &DeleteAccountNotFound{}
}

/*DeleteAccountNotFound handles this case with default header values.

The account was not found
*/
type DeleteAccountNotFound struct {
	Payload *models.Error
}

func (o *DeleteAccountNotFound) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{clusterId}/account/{username}][%d] deleteAccountNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountDefault creates a DeleteAccountDefault with default headers values
func NewDeleteAccountDefault(code int) *DeleteAccountDefault {
	return &DeleteAccountDefault{
		_statusCode: code,
	}
}

/*DeleteAccountDefault handles this case with default header values.

Error
*/
type DeleteAccountDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete account default response
func (o *DeleteAccountDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAccountDefault) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{clusterId}/account/{username}][%d] deleteAccount default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
