// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAccountParams creates a new DeleteAccountParams object
// with the default values initialized.
func NewDeleteAccountParams() *DeleteAccountParams {
	var ()
	return &DeleteAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAccountParamsWithTimeout creates a new DeleteAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAccountParamsWithTimeout(timeout time.Duration) *DeleteAccountParams {
	var ()
	return &DeleteAccountParams{

		timeout: timeout,
	}
}

// NewDeleteAccountParamsWithContext creates a new DeleteAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAccountParamsWithContext(ctx context.Context) *DeleteAccountParams {
	var ()
	return &DeleteAccountParams{

		Context: ctx,
	}
}

// NewDeleteAccountParamsWithHTTPClient creates a new DeleteAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAccountParamsWithHTTPClient(client *http.Client) *DeleteAccountParams {
	var ()
	return &DeleteAccountParams{
		HTTPClient: client,
	}
}

/*DeleteAccountParams contains all the parameters to send to the API endpoint
for the delete account operation typically these are written to a http.Request
*/
type DeleteAccountParams struct {

	/*ClusterID
	  the clusterId to be queried

	*/
	ClusterID string
	/*Username
	  the name for the user that gathered the account

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete account params
func (o *DeleteAccountParams) WithTimeout(timeout time.Duration) *DeleteAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete account params
func (o *DeleteAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete account params
func (o *DeleteAccountParams) WithContext(ctx context.Context) *DeleteAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete account params
func (o *DeleteAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete account params
func (o *DeleteAccountParams) WithHTTPClient(client *http.Client) *DeleteAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete account params
func (o *DeleteAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the delete account params
func (o *DeleteAccountParams) WithClusterID(clusterID string) *DeleteAccountParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the delete account params
func (o *DeleteAccountParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithUsername adds the username to the delete account params
func (o *DeleteAccountParams) WithUsername(username string) *DeleteAccountParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the delete account params
func (o *DeleteAccountParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clusterId
	if err := r.SetPathParam("clusterId", o.ClusterID); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
