// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFetchUserClustersParams creates a new FetchUserClustersParams object
// with the default values initialized.
func NewFetchUserClustersParams() *FetchUserClustersParams {
	var ()
	return &FetchUserClustersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFetchUserClustersParamsWithTimeout creates a new FetchUserClustersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFetchUserClustersParamsWithTimeout(timeout time.Duration) *FetchUserClustersParams {
	var ()
	return &FetchUserClustersParams{

		timeout: timeout,
	}
}

// NewFetchUserClustersParamsWithContext creates a new FetchUserClustersParams object
// with the default values initialized, and the ability to set a context for a request
func NewFetchUserClustersParamsWithContext(ctx context.Context) *FetchUserClustersParams {
	var ()
	return &FetchUserClustersParams{

		Context: ctx,
	}
}

// NewFetchUserClustersParamsWithHTTPClient creates a new FetchUserClustersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFetchUserClustersParamsWithHTTPClient(client *http.Client) *FetchUserClustersParams {
	var ()
	return &FetchUserClustersParams{
		HTTPClient: client,
	}
}

/*FetchUserClustersParams contains all the parameters to send to the API endpoint
for the fetch user clusters operation typically these are written to a http.Request
*/
type FetchUserClustersParams struct {

	/*Username
	  the name of a user

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the fetch user clusters params
func (o *FetchUserClustersParams) WithTimeout(timeout time.Duration) *FetchUserClustersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fetch user clusters params
func (o *FetchUserClustersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fetch user clusters params
func (o *FetchUserClustersParams) WithContext(ctx context.Context) *FetchUserClustersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fetch user clusters params
func (o *FetchUserClustersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the fetch user clusters params
func (o *FetchUserClustersParams) WithHTTPClient(client *http.Client) *FetchUserClustersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the fetch user clusters params
func (o *FetchUserClustersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUsername adds the username to the fetch user clusters params
func (o *FetchUserClustersParams) WithUsername(username string) *FetchUserClustersParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the fetch user clusters params
func (o *FetchUserClustersParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *FetchUserClustersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
