// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/superkomputer/apiclient/models"
)

// GetAccountReader is a Reader for the GetAccount structure.
type GetAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAccountOK creates a GetAccountOK with default headers values
func NewGetAccountOK() *GetAccountOK {
	return &GetAccountOK{}
}

/*GetAccountOK handles this case with default header values.

200 response with account information
*/
type GetAccountOK struct {
	Payload *models.Account
}

func (o *GetAccountOK) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}/account/{username}][%d] getAccountOK  %+v", 200, o.Payload)
}

func (o *GetAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Account)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountNotFound creates a GetAccountNotFound with default headers values
func NewGetAccountNotFound() *GetAccountNotFound {
	return &GetAccountNotFound{}
}

/*GetAccountNotFound handles this case with default header values.

The account was not found
*/
type GetAccountNotFound struct {
	Payload *models.Error
}

func (o *GetAccountNotFound) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}/account/{username}][%d] getAccountNotFound  %+v", 404, o.Payload)
}

func (o *GetAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountDefault creates a GetAccountDefault with default headers values
func NewGetAccountDefault(code int) *GetAccountDefault {
	return &GetAccountDefault{
		_statusCode: code,
	}
}

/*GetAccountDefault handles this case with default header values.

Error
*/
type GetAccountDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get account default response
func (o *GetAccountDefault) Code() int {
	return o._statusCode
}

func (o *GetAccountDefault) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}/account/{username}][%d] getAccount default  %+v", o._statusCode, o.Payload)
}

func (o *GetAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
